name: machine_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - pandas=2.2.2
  - matplotlib=3.9.2
  - ipykernel
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - pyarrow=17.0.0
  - ipympl=0.9.4
  - geopandas=1.0.1
  - folium=0.17.0
